version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER : abhishek
      POSTGRES_PASSWORD: abhishek2610
      POSTGRES_DB: codeDB
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

      
  adminer:
    image: adminer
    container_name: my_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pg_data:
